data:
  test_ratio: 0.15
  train_ratio: 0.7
  val_ratio: 0.15
dataset_version: v1
hyperparameter_tuning:
  enabled: false
  parameters:
    conv_filters:
    - - 16
      - 32
      - 64
    - - 32
      - 64
      - 128
    - - 64
      - 128
      - 256
    learning_rate:
    - 0.0001
    - 0.001
    - 0.01
model:
  batch_size: 64
  conv_filters:
  - 32
  - 64
  - 128
  conv_layers: 3
  dropout_rate: 0.25
  epochs: 10
  kernel_sizes:
  - 3
  - 3
  - 3
  learning_rate: 0.001
random_seed: 26
