name: handwriting-recognition
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip>=21.0
  - pip:
    - mlflow>=2.0.0
    - tensorflow>=2.9.0
    - keras>=2.9.0
    - matplotlib>=3.5.0
    - numpy>=1.19.0
    - flask>=2.0.0
    - pillow>=9.0.0
    - scikit-learn>=1.0.0
    - pandas>=1.3.0